import type { Lead } from './types';

export function toLeadDbRow(lead: Lead, organizationId: string | null) {
  return {
    biz_name: lead.bizName,
    biz_id: lead.bizId || null,
    license_date: lead.licenseDate || null,
    last_modified_date: lead.lastModifiedDate || null,
    road_address: lead.roadAddress || null,
    lot_address: lead.lotAddress || null,
    coord_x: lead.coordX || null,
    coord_y: lead.coordY || null,
    latitude: lead.latitude || null,
    longitude: lead.longitude || null,
    phone: lead.phone || null,
    medical_subject: lead.medicalSubject || null,
    mgt_no: lead.mgtNo || null,
    operating_status: lead.operatingStatus || null,
    detailed_status: lead.detailedStatus || null,
    category: lead.category || 'OTHER',
    service_id: lead.serviceId || null,
    service_name: lead.serviceName || null,
    nearest_station: lead.nearestStation || null,
    station_distance: lead.stationDistance ? Math.round(lead.stationDistance) : null,
    station_lines: lead.stationLines || null,
    nearest_exit_no: lead.nearestExitNo || null,
    status: lead.status || 'NEW',
    notes: lead.notes || null,
    sopo_bizes_id: lead.sopoBizesId || null,
    sopo_biz_name: lead.sopoBizName || null,
    sopo_road_address: lead.sopoRoadAddress || null,
    sopo_lot_address: lead.sopoLotAddress || null,
    sopo_latitude: lead.sopoLatitude || null,
    sopo_longitude: lead.sopoLongitude || null,
    sopo_category_large: lead.sopoCategoryLarge || null,
    sopo_category_large_name: lead.sopoCategoryLargeName || null,
    sopo_category_middle: lead.sopoCategoryMiddle || null,
    sopo_category_middle_name: lead.sopoCategoryMiddleName || null,
    sopo_category_small: lead.sopoCategorySmall || null,
    sopo_category_small_name: lead.sopoCategorySmallName || null,
    sopo_province_code: lead.sopoProvinceCode || null,
    sopo_province_name: lead.sopoProvinceName || null,
    sopo_district_code: lead.sopoDistrictCode || null,
    sopo_district_name: lead.sopoDistrictName || null,
    sopo_dong_code: lead.sopoDongCode || null,
    sopo_dong_name: lead.sopoDongName || null,
    sopo_std_ym: lead.sopoStdYm || null,
    sopo_data_fetched_at: lead.sopoDataFetchedAt || null,
    organization_id: organizationId,
  };
}
